// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc1
// source: proto/analytics_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetDashboardMetrics_FullMethodName            = "/analytics.AnalyticsService/GetDashboardMetrics"
	AnalyticsService_GetRevenueReport_FullMethodName               = "/analytics.AnalyticsService/GetRevenueReport"
	AnalyticsService_GetPaymentMethodsReport_FullMethodName        = "/analytics.AnalyticsService/GetPaymentMethodsReport"
	AnalyticsService_GetOutstandingInvoicesReport_FullMethodName   = "/analytics.AnalyticsService/GetOutstandingInvoicesReport"
	AnalyticsService_GetMedicalSchemeReport_FullMethodName         = "/analytics.AnalyticsService/GetMedicalSchemeReport"
	AnalyticsService_GetDepartmentRevenueReport_FullMethodName     = "/analytics.AnalyticsService/GetDepartmentRevenueReport"
	AnalyticsService_GetPOSSalesReport_FullMethodName              = "/analytics.AnalyticsService/GetPOSSalesReport"
	AnalyticsService_GetTopSellingMedicationsReport_FullMethodName = "/analytics.AnalyticsService/GetTopSellingMedicationsReport"
	AnalyticsService_GetLowStockReport_FullMethodName              = "/analytics.AnalyticsService/GetLowStockReport"
	AnalyticsService_GetStockMovementReport_FullMethodName         = "/analytics.AnalyticsService/GetStockMovementReport"
	AnalyticsService_GetExpiringMedicationsReport_FullMethodName   = "/analytics.AnalyticsService/GetExpiringMedicationsReport"
	AnalyticsService_GetMedicationSalesTrendsReport_FullMethodName = "/analytics.AnalyticsService/GetMedicationSalesTrendsReport"
	AnalyticsService_GetPatientRegistrationReport_FullMethodName   = "/analytics.AnalyticsService/GetPatientRegistrationReport"
	AnalyticsService_GetActivePatientReport_FullMethodName         = "/analytics.AnalyticsService/GetActivePatientReport"
	AnalyticsService_GetPatientBillingReport_FullMethodName        = "/analytics.AnalyticsService/GetPatientBillingReport"
	AnalyticsService_GetPayrollReport_FullMethodName               = "/analytics.AnalyticsService/GetPayrollReport"
	AnalyticsService_GetAttendanceReport_FullMethodName            = "/analytics.AnalyticsService/GetAttendanceReport"
	AnalyticsService_GetLeaveReport_FullMethodName                 = "/analytics.AnalyticsService/GetLeaveReport"
	AnalyticsService_GetCashierPerformanceReport_FullMethodName    = "/analytics.AnalyticsService/GetCashierPerformanceReport"
	AnalyticsService_GetSalesByTimeReport_FullMethodName           = "/analytics.AnalyticsService/GetSalesByTimeReport"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalyticsService defines the service for generating reports and analytics
type AnalyticsServiceClient interface {
	// Dashboard Metrics
	GetDashboardMetrics(ctx context.Context, in *GetDashboardMetricsRequest, opts ...grpc.CallOption) (*GetDashboardMetricsResponse, error)
	// Financial Reports
	GetRevenueReport(ctx context.Context, in *GetRevenueReportRequest, opts ...grpc.CallOption) (*GetRevenueReportResponse, error)
	GetPaymentMethodsReport(ctx context.Context, in *GetPaymentMethodsReportRequest, opts ...grpc.CallOption) (*GetPaymentMethodsReportResponse, error)
	GetOutstandingInvoicesReport(ctx context.Context, in *GetOutstandingInvoicesReportRequest, opts ...grpc.CallOption) (*GetOutstandingInvoicesReportResponse, error)
	GetMedicalSchemeReport(ctx context.Context, in *GetMedicalSchemeReportRequest, opts ...grpc.CallOption) (*GetMedicalSchemeReportResponse, error)
	GetDepartmentRevenueReport(ctx context.Context, in *GetDepartmentRevenueReportRequest, opts ...grpc.CallOption) (*GetDepartmentRevenueReportResponse, error)
	// Pharmacy Reports
	GetPOSSalesReport(ctx context.Context, in *GetPOSSalesReportRequest, opts ...grpc.CallOption) (*GetPOSSalesReportResponse, error)
	GetTopSellingMedicationsReport(ctx context.Context, in *GetTopSellingMedicationsReportRequest, opts ...grpc.CallOption) (*GetTopSellingMedicationsReportResponse, error)
	GetLowStockReport(ctx context.Context, in *GetLowStockReportRequest, opts ...grpc.CallOption) (*GetLowStockReportResponse, error)
	GetStockMovementReport(ctx context.Context, in *GetStockMovementReportRequest, opts ...grpc.CallOption) (*GetStockMovementReportResponse, error)
	GetExpiringMedicationsReport(ctx context.Context, in *GetExpiringMedicationsReportRequest, opts ...grpc.CallOption) (*GetExpiringMedicationsReportResponse, error)
	GetMedicationSalesTrendsReport(ctx context.Context, in *GetMedicationSalesTrendsReportRequest, opts ...grpc.CallOption) (*GetMedicationSalesTrendsReportResponse, error)
	// Patient Reports
	GetPatientRegistrationReport(ctx context.Context, in *GetPatientRegistrationReportRequest, opts ...grpc.CallOption) (*GetPatientRegistrationReportResponse, error)
	GetActivePatientReport(ctx context.Context, in *GetActivePatientReportRequest, opts ...grpc.CallOption) (*GetActivePatientReportResponse, error)
	GetPatientBillingReport(ctx context.Context, in *GetPatientBillingReportRequest, opts ...grpc.CallOption) (*GetPatientBillingReportResponse, error)
	// HR Reports
	GetPayrollReport(ctx context.Context, in *GetPayrollReportRequest, opts ...grpc.CallOption) (*GetPayrollReportResponse, error)
	GetAttendanceReport(ctx context.Context, in *GetAttendanceReportRequest, opts ...grpc.CallOption) (*GetAttendanceReportResponse, error)
	GetLeaveReport(ctx context.Context, in *GetLeaveReportRequest, opts ...grpc.CallOption) (*GetLeaveReportResponse, error)
	// Operational Reports
	GetCashierPerformanceReport(ctx context.Context, in *GetCashierPerformanceReportRequest, opts ...grpc.CallOption) (*GetCashierPerformanceReportResponse, error)
	GetSalesByTimeReport(ctx context.Context, in *GetSalesByTimeReportRequest, opts ...grpc.CallOption) (*GetSalesByTimeReportResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetDashboardMetrics(ctx context.Context, in *GetDashboardMetricsRequest, opts ...grpc.CallOption) (*GetDashboardMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardMetricsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDashboardMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRevenueReport(ctx context.Context, in *GetRevenueReportRequest, opts ...grpc.CallOption) (*GetRevenueReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevenueReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRevenueReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPaymentMethodsReport(ctx context.Context, in *GetPaymentMethodsReportRequest, opts ...grpc.CallOption) (*GetPaymentMethodsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentMethodsReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPaymentMethodsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetOutstandingInvoicesReport(ctx context.Context, in *GetOutstandingInvoicesReportRequest, opts ...grpc.CallOption) (*GetOutstandingInvoicesReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOutstandingInvoicesReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOutstandingInvoicesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMedicalSchemeReport(ctx context.Context, in *GetMedicalSchemeReportRequest, opts ...grpc.CallOption) (*GetMedicalSchemeReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedicalSchemeReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMedicalSchemeReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDepartmentRevenueReport(ctx context.Context, in *GetDepartmentRevenueReportRequest, opts ...grpc.CallOption) (*GetDepartmentRevenueReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentRevenueReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDepartmentRevenueReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPOSSalesReport(ctx context.Context, in *GetPOSSalesReportRequest, opts ...grpc.CallOption) (*GetPOSSalesReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPOSSalesReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPOSSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopSellingMedicationsReport(ctx context.Context, in *GetTopSellingMedicationsReportRequest, opts ...grpc.CallOption) (*GetTopSellingMedicationsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopSellingMedicationsReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopSellingMedicationsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetLowStockReport(ctx context.Context, in *GetLowStockReportRequest, opts ...grpc.CallOption) (*GetLowStockReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLowStockReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetLowStockReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetStockMovementReport(ctx context.Context, in *GetStockMovementReportRequest, opts ...grpc.CallOption) (*GetStockMovementReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockMovementReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetStockMovementReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetExpiringMedicationsReport(ctx context.Context, in *GetExpiringMedicationsReportRequest, opts ...grpc.CallOption) (*GetExpiringMedicationsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpiringMedicationsReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetExpiringMedicationsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMedicationSalesTrendsReport(ctx context.Context, in *GetMedicationSalesTrendsReportRequest, opts ...grpc.CallOption) (*GetMedicationSalesTrendsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedicationSalesTrendsReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMedicationSalesTrendsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPatientRegistrationReport(ctx context.Context, in *GetPatientRegistrationReportRequest, opts ...grpc.CallOption) (*GetPatientRegistrationReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPatientRegistrationReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPatientRegistrationReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetActivePatientReport(ctx context.Context, in *GetActivePatientReportRequest, opts ...grpc.CallOption) (*GetActivePatientReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivePatientReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetActivePatientReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPatientBillingReport(ctx context.Context, in *GetPatientBillingReportRequest, opts ...grpc.CallOption) (*GetPatientBillingReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPatientBillingReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPatientBillingReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPayrollReport(ctx context.Context, in *GetPayrollReportRequest, opts ...grpc.CallOption) (*GetPayrollReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayrollReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPayrollReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAttendanceReport(ctx context.Context, in *GetAttendanceReportRequest, opts ...grpc.CallOption) (*GetAttendanceReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAttendanceReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetLeaveReport(ctx context.Context, in *GetLeaveReportRequest, opts ...grpc.CallOption) (*GetLeaveReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaveReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetLeaveReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCashierPerformanceReport(ctx context.Context, in *GetCashierPerformanceReportRequest, opts ...grpc.CallOption) (*GetCashierPerformanceReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCashierPerformanceReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCashierPerformanceReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetSalesByTimeReport(ctx context.Context, in *GetSalesByTimeReportRequest, opts ...grpc.CallOption) (*GetSalesByTimeReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSalesByTimeReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetSalesByTimeReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// AnalyticsService defines the service for generating reports and analytics
type AnalyticsServiceServer interface {
	// Dashboard Metrics
	GetDashboardMetrics(context.Context, *GetDashboardMetricsRequest) (*GetDashboardMetricsResponse, error)
	// Financial Reports
	GetRevenueReport(context.Context, *GetRevenueReportRequest) (*GetRevenueReportResponse, error)
	GetPaymentMethodsReport(context.Context, *GetPaymentMethodsReportRequest) (*GetPaymentMethodsReportResponse, error)
	GetOutstandingInvoicesReport(context.Context, *GetOutstandingInvoicesReportRequest) (*GetOutstandingInvoicesReportResponse, error)
	GetMedicalSchemeReport(context.Context, *GetMedicalSchemeReportRequest) (*GetMedicalSchemeReportResponse, error)
	GetDepartmentRevenueReport(context.Context, *GetDepartmentRevenueReportRequest) (*GetDepartmentRevenueReportResponse, error)
	// Pharmacy Reports
	GetPOSSalesReport(context.Context, *GetPOSSalesReportRequest) (*GetPOSSalesReportResponse, error)
	GetTopSellingMedicationsReport(context.Context, *GetTopSellingMedicationsReportRequest) (*GetTopSellingMedicationsReportResponse, error)
	GetLowStockReport(context.Context, *GetLowStockReportRequest) (*GetLowStockReportResponse, error)
	GetStockMovementReport(context.Context, *GetStockMovementReportRequest) (*GetStockMovementReportResponse, error)
	GetExpiringMedicationsReport(context.Context, *GetExpiringMedicationsReportRequest) (*GetExpiringMedicationsReportResponse, error)
	GetMedicationSalesTrendsReport(context.Context, *GetMedicationSalesTrendsReportRequest) (*GetMedicationSalesTrendsReportResponse, error)
	// Patient Reports
	GetPatientRegistrationReport(context.Context, *GetPatientRegistrationReportRequest) (*GetPatientRegistrationReportResponse, error)
	GetActivePatientReport(context.Context, *GetActivePatientReportRequest) (*GetActivePatientReportResponse, error)
	GetPatientBillingReport(context.Context, *GetPatientBillingReportRequest) (*GetPatientBillingReportResponse, error)
	// HR Reports
	GetPayrollReport(context.Context, *GetPayrollReportRequest) (*GetPayrollReportResponse, error)
	GetAttendanceReport(context.Context, *GetAttendanceReportRequest) (*GetAttendanceReportResponse, error)
	GetLeaveReport(context.Context, *GetLeaveReportRequest) (*GetLeaveReportResponse, error)
	// Operational Reports
	GetCashierPerformanceReport(context.Context, *GetCashierPerformanceReportRequest) (*GetCashierPerformanceReportResponse, error)
	GetSalesByTimeReport(context.Context, *GetSalesByTimeReportRequest) (*GetSalesByTimeReportResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetDashboardMetrics(context.Context, *GetDashboardMetricsRequest) (*GetDashboardMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRevenueReport(context.Context, *GetRevenueReportRequest) (*GetRevenueReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevenueReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPaymentMethodsReport(context.Context, *GetPaymentMethodsReportRequest) (*GetPaymentMethodsReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethodsReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetOutstandingInvoicesReport(context.Context, *GetOutstandingInvoicesReportRequest) (*GetOutstandingInvoicesReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutstandingInvoicesReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMedicalSchemeReport(context.Context, *GetMedicalSchemeReportRequest) (*GetMedicalSchemeReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedicalSchemeReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDepartmentRevenueReport(context.Context, *GetDepartmentRevenueReportRequest) (*GetDepartmentRevenueReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentRevenueReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPOSSalesReport(context.Context, *GetPOSSalesReportRequest) (*GetPOSSalesReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPOSSalesReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopSellingMedicationsReport(context.Context, *GetTopSellingMedicationsReportRequest) (*GetTopSellingMedicationsReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopSellingMedicationsReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetLowStockReport(context.Context, *GetLowStockReportRequest) (*GetLowStockReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLowStockReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetStockMovementReport(context.Context, *GetStockMovementReportRequest) (*GetStockMovementReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockMovementReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetExpiringMedicationsReport(context.Context, *GetExpiringMedicationsReportRequest) (*GetExpiringMedicationsReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpiringMedicationsReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMedicationSalesTrendsReport(context.Context, *GetMedicationSalesTrendsReportRequest) (*GetMedicationSalesTrendsReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedicationSalesTrendsReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPatientRegistrationReport(context.Context, *GetPatientRegistrationReportRequest) (*GetPatientRegistrationReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatientRegistrationReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetActivePatientReport(context.Context, *GetActivePatientReportRequest) (*GetActivePatientReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivePatientReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPatientBillingReport(context.Context, *GetPatientBillingReportRequest) (*GetPatientBillingReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatientBillingReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPayrollReport(context.Context, *GetPayrollReportRequest) (*GetPayrollReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayrollReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAttendanceReport(context.Context, *GetAttendanceReportRequest) (*GetAttendanceReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetLeaveReport(context.Context, *GetLeaveReportRequest) (*GetLeaveReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaveReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCashierPerformanceReport(context.Context, *GetCashierPerformanceReportRequest) (*GetCashierPerformanceReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCashierPerformanceReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetSalesByTimeReport(context.Context, *GetSalesByTimeReportRequest) (*GetSalesByTimeReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesByTimeReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetDashboardMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDashboardMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDashboardMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDashboardMetrics(ctx, req.(*GetDashboardMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRevenueReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRevenueReport(ctx, req.(*GetRevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPaymentMethodsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPaymentMethodsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPaymentMethodsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPaymentMethodsReport(ctx, req.(*GetPaymentMethodsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetOutstandingInvoicesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutstandingInvoicesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOutstandingInvoicesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOutstandingInvoicesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOutstandingInvoicesReport(ctx, req.(*GetOutstandingInvoicesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMedicalSchemeReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedicalSchemeReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMedicalSchemeReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMedicalSchemeReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMedicalSchemeReport(ctx, req.(*GetMedicalSchemeReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDepartmentRevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentRevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDepartmentRevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDepartmentRevenueReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDepartmentRevenueReport(ctx, req.(*GetDepartmentRevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPOSSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPOSSalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPOSSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPOSSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPOSSalesReport(ctx, req.(*GetPOSSalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopSellingMedicationsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopSellingMedicationsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopSellingMedicationsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopSellingMedicationsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopSellingMedicationsReport(ctx, req.(*GetTopSellingMedicationsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetLowStockReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLowStockReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetLowStockReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetLowStockReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetLowStockReport(ctx, req.(*GetLowStockReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetStockMovementReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockMovementReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetStockMovementReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetStockMovementReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetStockMovementReport(ctx, req.(*GetStockMovementReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetExpiringMedicationsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpiringMedicationsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetExpiringMedicationsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetExpiringMedicationsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetExpiringMedicationsReport(ctx, req.(*GetExpiringMedicationsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMedicationSalesTrendsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedicationSalesTrendsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMedicationSalesTrendsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMedicationSalesTrendsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMedicationSalesTrendsReport(ctx, req.(*GetMedicationSalesTrendsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPatientRegistrationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatientRegistrationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPatientRegistrationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPatientRegistrationReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPatientRegistrationReport(ctx, req.(*GetPatientRegistrationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetActivePatientReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivePatientReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetActivePatientReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetActivePatientReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetActivePatientReport(ctx, req.(*GetActivePatientReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPatientBillingReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatientBillingReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPatientBillingReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPatientBillingReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPatientBillingReport(ctx, req.(*GetPatientBillingReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPayrollReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayrollReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPayrollReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPayrollReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPayrollReport(ctx, req.(*GetPayrollReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAttendanceReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAttendanceReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAttendanceReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAttendanceReport(ctx, req.(*GetAttendanceReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetLeaveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetLeaveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetLeaveReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetLeaveReport(ctx, req.(*GetLeaveReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCashierPerformanceReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCashierPerformanceReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCashierPerformanceReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCashierPerformanceReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCashierPerformanceReport(ctx, req.(*GetCashierPerformanceReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetSalesByTimeReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesByTimeReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetSalesByTimeReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetSalesByTimeReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetSalesByTimeReport(ctx, req.(*GetSalesByTimeReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardMetrics",
			Handler:    _AnalyticsService_GetDashboardMetrics_Handler,
		},
		{
			MethodName: "GetRevenueReport",
			Handler:    _AnalyticsService_GetRevenueReport_Handler,
		},
		{
			MethodName: "GetPaymentMethodsReport",
			Handler:    _AnalyticsService_GetPaymentMethodsReport_Handler,
		},
		{
			MethodName: "GetOutstandingInvoicesReport",
			Handler:    _AnalyticsService_GetOutstandingInvoicesReport_Handler,
		},
		{
			MethodName: "GetMedicalSchemeReport",
			Handler:    _AnalyticsService_GetMedicalSchemeReport_Handler,
		},
		{
			MethodName: "GetDepartmentRevenueReport",
			Handler:    _AnalyticsService_GetDepartmentRevenueReport_Handler,
		},
		{
			MethodName: "GetPOSSalesReport",
			Handler:    _AnalyticsService_GetPOSSalesReport_Handler,
		},
		{
			MethodName: "GetTopSellingMedicationsReport",
			Handler:    _AnalyticsService_GetTopSellingMedicationsReport_Handler,
		},
		{
			MethodName: "GetLowStockReport",
			Handler:    _AnalyticsService_GetLowStockReport_Handler,
		},
		{
			MethodName: "GetStockMovementReport",
			Handler:    _AnalyticsService_GetStockMovementReport_Handler,
		},
		{
			MethodName: "GetExpiringMedicationsReport",
			Handler:    _AnalyticsService_GetExpiringMedicationsReport_Handler,
		},
		{
			MethodName: "GetMedicationSalesTrendsReport",
			Handler:    _AnalyticsService_GetMedicationSalesTrendsReport_Handler,
		},
		{
			MethodName: "GetPatientRegistrationReport",
			Handler:    _AnalyticsService_GetPatientRegistrationReport_Handler,
		},
		{
			MethodName: "GetActivePatientReport",
			Handler:    _AnalyticsService_GetActivePatientReport_Handler,
		},
		{
			MethodName: "GetPatientBillingReport",
			Handler:    _AnalyticsService_GetPatientBillingReport_Handler,
		},
		{
			MethodName: "GetPayrollReport",
			Handler:    _AnalyticsService_GetPayrollReport_Handler,
		},
		{
			MethodName: "GetAttendanceReport",
			Handler:    _AnalyticsService_GetAttendanceReport_Handler,
		},
		{
			MethodName: "GetLeaveReport",
			Handler:    _AnalyticsService_GetLeaveReport_Handler,
		},
		{
			MethodName: "GetCashierPerformanceReport",
			Handler:    _AnalyticsService_GetCashierPerformanceReport_Handler,
		},
		{
			MethodName: "GetSalesByTimeReport",
			Handler:    _AnalyticsService_GetSalesByTimeReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics_service.proto",
}
