// services/action-permissions-service/proto/action_permissions_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc1
// source: action_permissions_service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckActionPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRoles     []string               `protobuf:"bytes,4,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckActionPermissionRequest) Reset() {
	*x = CheckActionPermissionRequest{}
	mi := &file_action_permissions_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckActionPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckActionPermissionRequest) ProtoMessage() {}

func (x *CheckActionPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckActionPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckActionPermissionRequest) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckActionPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckActionPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckActionPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckActionPermissionRequest) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type CheckActionPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckActionPermissionResponse) Reset() {
	*x = CheckActionPermissionResponse{}
	mi := &file_action_permissions_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckActionPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckActionPermissionResponse) ProtoMessage() {}

func (x *CheckActionPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckActionPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckActionPermissionResponse) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckActionPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

type ActionPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Users         []string               `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionPermission) Reset() {
	*x = ActionPermission{}
	mi := &file_action_permissions_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionPermission) ProtoMessage() {}

func (x *ActionPermission) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionPermission.ProtoReflect.Descriptor instead.
func (*ActionPermission) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{2}
}

func (x *ActionPermission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ActionPermission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionPermission) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ActionPermission) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetAllActionPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActionPermissionsRequest) Reset() {
	*x = GetAllActionPermissionsRequest{}
	mi := &file_action_permissions_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActionPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActionPermissionsRequest) ProtoMessage() {}

func (x *GetAllActionPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActionPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllActionPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{3}
}

type GetAllActionPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*ActionPermission    `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActionPermissionsResponse) Reset() {
	*x = GetAllActionPermissionsResponse{}
	mi := &file_action_permissions_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActionPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActionPermissionsResponse) ProtoMessage() {}

func (x *GetAllActionPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActionPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllActionPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllActionPermissionsResponse) GetPermissions() []*ActionPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateActionPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Users         []string               `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActionPermissionRequest) Reset() {
	*x = UpdateActionPermissionRequest{}
	mi := &file_action_permissions_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActionPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionPermissionRequest) ProtoMessage() {}

func (x *UpdateActionPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionPermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdateActionPermissionRequest) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateActionPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UpdateActionPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateActionPermissionRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UpdateActionPermissionRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateActionPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActionPermissionResponse) Reset() {
	*x = UpdateActionPermissionResponse{}
	mi := &file_action_permissions_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActionPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionPermissionResponse) ProtoMessage() {}

func (x *UpdateActionPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionPermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdateActionPermissionResponse) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateActionPermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddActionPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Users         []string               `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddActionPermissionRequest) Reset() {
	*x = AddActionPermissionRequest{}
	mi := &file_action_permissions_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActionPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionPermissionRequest) ProtoMessage() {}

func (x *AddActionPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionPermissionRequest.ProtoReflect.Descriptor instead.
func (*AddActionPermissionRequest) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddActionPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AddActionPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AddActionPermissionRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AddActionPermissionRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddActionPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddActionPermissionResponse) Reset() {
	*x = AddActionPermissionResponse{}
	mi := &file_action_permissions_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActionPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionPermissionResponse) ProtoMessage() {}

func (x *AddActionPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_permissions_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionPermissionResponse.ProtoReflect.Descriptor instead.
func (*AddActionPermissionResponse) Descriptor() ([]byte, []int) {
	return file_action_permissions_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddActionPermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_action_permissions_service_proto protoreflect.FileDescriptor

const file_action_permissions_service_proto_rawDesc = "" +
	"\n" +
	" action_permissions_service.proto\x12\x12action_permissions\x1a\x1cgoogle/api/annotations.proto\"\x8a\x01\n" +
	"\x1cCheckActionPermissionRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x04 \x03(\tR\tuserRoles\"F\n" +
	"\x1dCheckActionPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\"r\n" +
	"\x10ActionPermission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x14\n" +
	"\x05users\x18\x04 \x03(\tR\x05users\" \n" +
	"\x1eGetAllActionPermissionsRequest\"i\n" +
	"\x1fGetAllActionPermissionsResponse\x12F\n" +
	"\vpermissions\x18\x01 \x03(\v2$.action_permissions.ActionPermissionR\vpermissions\"\x7f\n" +
	"\x1dUpdateActionPermissionRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x14\n" +
	"\x05users\x18\x04 \x03(\tR\x05users\":\n" +
	"\x1eUpdateActionPermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"|\n" +
	"\x1aAddActionPermissionRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x14\n" +
	"\x05users\x18\x04 \x03(\tR\x05users\"7\n" +
	"\x1bAddActionPermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa7\x05\n" +
	"\x17ActionPermissionService\x12\xa5\x01\n" +
	"\x15CheckActionPermission\x120.action_permissions.CheckActionPermissionRequest\x1a1.action_permissions.CheckActionPermissionResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/action-permissions/check\x12\xa2\x01\n" +
	"\x17GetAllActionPermissions\x122.action_permissions.GetAllActionPermissionsRequest\x1a3.action_permissions.GetAllActionPermissionsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/action-permissions\x12\xa2\x01\n" +
	"\x16UpdateActionPermission\x121.action_permissions.UpdateActionPermissionRequest\x1a2.action_permissions.UpdateActionPermissionResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/action-permissions\x12\x99\x01\n" +
	"\x13AddActionPermission\x12..action_permissions.AddActionPermissionRequest\x1a/.action_permissions.AddActionPermissionResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/action-permissionsB+Z)./shared/action-permissions-service/protob\x06proto3"

var (
	file_action_permissions_service_proto_rawDescOnce sync.Once
	file_action_permissions_service_proto_rawDescData []byte
)

func file_action_permissions_service_proto_rawDescGZIP() []byte {
	file_action_permissions_service_proto_rawDescOnce.Do(func() {
		file_action_permissions_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_permissions_service_proto_rawDesc), len(file_action_permissions_service_proto_rawDesc)))
	})
	return file_action_permissions_service_proto_rawDescData
}

var file_action_permissions_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_action_permissions_service_proto_goTypes = []any{
	(*CheckActionPermissionRequest)(nil),    // 0: action_permissions.CheckActionPermissionRequest
	(*CheckActionPermissionResponse)(nil),   // 1: action_permissions.CheckActionPermissionResponse
	(*ActionPermission)(nil),                // 2: action_permissions.ActionPermission
	(*GetAllActionPermissionsRequest)(nil),  // 3: action_permissions.GetAllActionPermissionsRequest
	(*GetAllActionPermissionsResponse)(nil), // 4: action_permissions.GetAllActionPermissionsResponse
	(*UpdateActionPermissionRequest)(nil),   // 5: action_permissions.UpdateActionPermissionRequest
	(*UpdateActionPermissionResponse)(nil),  // 6: action_permissions.UpdateActionPermissionResponse
	(*AddActionPermissionRequest)(nil),      // 7: action_permissions.AddActionPermissionRequest
	(*AddActionPermissionResponse)(nil),     // 8: action_permissions.AddActionPermissionResponse
}
var file_action_permissions_service_proto_depIdxs = []int32{
	2, // 0: action_permissions.GetAllActionPermissionsResponse.permissions:type_name -> action_permissions.ActionPermission
	0, // 1: action_permissions.ActionPermissionService.CheckActionPermission:input_type -> action_permissions.CheckActionPermissionRequest
	3, // 2: action_permissions.ActionPermissionService.GetAllActionPermissions:input_type -> action_permissions.GetAllActionPermissionsRequest
	5, // 3: action_permissions.ActionPermissionService.UpdateActionPermission:input_type -> action_permissions.UpdateActionPermissionRequest
	7, // 4: action_permissions.ActionPermissionService.AddActionPermission:input_type -> action_permissions.AddActionPermissionRequest
	1, // 5: action_permissions.ActionPermissionService.CheckActionPermission:output_type -> action_permissions.CheckActionPermissionResponse
	4, // 6: action_permissions.ActionPermissionService.GetAllActionPermissions:output_type -> action_permissions.GetAllActionPermissionsResponse
	6, // 7: action_permissions.ActionPermissionService.UpdateActionPermission:output_type -> action_permissions.UpdateActionPermissionResponse
	8, // 8: action_permissions.ActionPermissionService.AddActionPermission:output_type -> action_permissions.AddActionPermissionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_permissions_service_proto_init() }
func file_action_permissions_service_proto_init() {
	if File_action_permissions_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_permissions_service_proto_rawDesc), len(file_action_permissions_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_action_permissions_service_proto_goTypes,
		DependencyIndexes: file_action_permissions_service_proto_depIdxs,
		MessageInfos:      file_action_permissions_service_proto_msgTypes,
	}.Build()
	File_action_permissions_service_proto = out.File
	file_action_permissions_service_proto_goTypes = nil
	file_action_permissions_service_proto_depIdxs = nil
}
